version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: "increase"
