version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include-scope: true
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "react"
        versions:
          - ">= 18.3.1"
      - dependency-name: "react-dom"
        versions:
          - ">= 18.3.1"

